name: Code checks
on:
  - push

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.10

      - name: Install Dependencies
        run: bun install

      - name: Unit Tests
        run: bun test

      - name: Lint
        run: bun lint

      - name: Code check
        run: bun check

      - name: Build
        run: bun build
