name: Code checks
on:
  - push

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Branch checkout
        uses: actions/checkout@v4.1.7

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.6.0

      - name: Use Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Unit Tests
        run: pnpm test

      - name: Lint
        run: pnpm lint

      - name: Code check
        run: pnpm check

      - name: Build
        run: pnpm build
