name: Code checks
on:
  - push

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2.0.2
        with:
          bun-version-file: "./package.json"

      - name: Install Dependencies
        run: bun install

      - name: Unit Tests
        run: bun run test

      - name: Lint
        run: bun run lint

      - name: Code check
        run: bun run check

      - name: Build
        run: bun run build

      - name: Pinned Dependencies Check
        run: bun ./bin/index.js --no-deps # Since this is a lib, it's ok to prod dependencies not to be pinned
