name: Quality and deploy
on:
  - push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Branch checkout
        uses: actions/checkout@v4.1.1

      - uses: pnpm/action-setup@v2
        with:
          version: 8.10.2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Unit Tests
        run: pnpm test

      - name: Lint
        run: pnpm lint

      - name: Code check
        run: pnpm check

      - name: Build
        run: pnpm build

      - name: Create Release Pull Request
        uses: changesets/action@v1
        if: github.ref == 'refs/heads/main'
        with:
          publish: pnpm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
